#page title
page_title                                : Juice                                     # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

github_link                               : https://github.com/tbwfdu/juice/releases  # Enter link to GitHub repository.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/juice.png                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Juice                                     # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_os                                    : apple                                     # Enter supported OS platforms - windows or apple
app_os_title                              : macOS
app_description                           : Workspace ONE Application Management Tool


# Information About Yourself
your_name                                 : Pete Lindley                                
your_link                                 : https://github.com/tbwfdu                     
your_city                                 : Down Under, Australia                                
email_address                             : thisispete@gmail.com
linkedin_username                         :                                           
linkedin_company                          :                                           
twitter_username                          : 
github_username                           : tbwfdu

# Feature List
features                                  :

  - title                                 : Over 7500+ Applications
    description                           : Juice has a database of over 7500 applications ready to import into Workspace ONE UEM.
    fontawesome_icon_name                 : database
    
  - title                                 : Over 1400+ Recipes
    description                           : Juice also supports PkgInfo recipes for additional metadata and configuration.
    fontawesome_icon_name                 : images

  - title                                 : Comprehensive Search
    description                           : Search for an Application by name and automatically create its corresponding Native App in Workspace ONE UEM.
    fontawesome_icon_name                 : search

  - title                                 : Identify Application Updates
    description                           : Query your existing Workspace ONE UEM App Catalog and identify available updates from the Juice database.
    fontawesome_icon_name                 : upload

  - title                                 : Import Directly into Workspace ONE
    description                           : Juice also parses the installer and generates the required metadata, removing the need to use Workspace ONE Admin Assistant.
    fontawesome_icon_name                 : file-import
    
  - title                                 : Edit Metadata & Add Scripts
    description                           : Add configuration from the PkgInfo recipe, automatically add scripts or edit the parsed metadata directly using Juice.
    fontawesome_icon_name                 : list



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_os                                 : macos                                     # Set to: macos or windows

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

windows_icon_color                        : "#0078D4"
apple_icon_color                          : "#666666"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
kramdown:
  toc_levels: 1..6